name: Deployment-of-python-app
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this has been triggered ${{ github.event_name }} event"
    - run: echo "This job is running on ${{ runner.os }} server hosted om github"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Style with pycodestyle
      run: |
        pycodestyle *.py
    - name: Unit testing
      run: |
        python3 -m doctest factorial.py
    - name: Build container
      run: |
        echo "Building a container image.."
        sleep 30
    - name: Deploy cluster
      run: |
        echo "Deploying to cluster..."
        sleep 30
        echo "Container has been deployed!"
    - run: echo "This job's status is ${{ job.status }}."
    
# name: Telerik-Github-Actions-Practice

# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
#     - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#     - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#     - name: Check out repository code
#       uses: actions/checkout@v2
#     - name: Set up Python 3.9
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint
#         pip install pycodestyle
#     - name: Lint with pylint
#       run: |
#         python lint_test.py
#     - name: Style with pycodestyle
#       run: |
#         pycodestyle *.py
#     - name: Unit testing
#       run: |
#         python3 -m doctest factorial.py
#     - name: Build container
#       run: echo "Building container iamge"
#     - name: Deploy
#       run: echo "Deploying to cluster"
